# fly.toml app configuration file for Flow Tasks
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flowtaks'
primary_region = 'iad'

[build]

[env]
  SPRING_PROFILES_ACTIVE = "prod"
  JAVA_OPTS = "-Xmx512m -Xms256m"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']



[[vm]]
  size = 'shared-cpu-2x'
  memory = '1gb'
